Add dockerfile and scripts for citus upgrade image

diff --git a/circleci/images/citusupgadetester/files/sbin/install-extdeps b/circleci/images/citusupgadetester/files/sbin/install-extdeps
--- a/circleci/images/citusupgadetester/files/sbin/install-extdeps
+++ b/circleci/images/citusupgadetester/files/sbin/install-extdeps
@@ -24,10 +24,24 @@ echo "Adding circleci user..." >&2
 groupadd -r circleci --gid=1729
 useradd -mg circleci --uid=1729 --shell=/bin/bash circleci
 
+echo "Running apt-get update..." >&2
+apt-get update
+apt-get install -y --no-install-recommends \
+  apt-transport-https \
+  ca-certificates \
+  curl \
+  debian-archive-keyring \
+  gcc 
+
 # import key and keep apt-key from issuing warnings
 echo "Importing PGDG key..." >&2
 curl -sf https://www.postgresql.org/media/keys/ACCC4CF8.asc | \
 APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 apt-key add -
+
+apt-get install -y python3-pip
+
+echo "Installing tools for failure testing..." >&2
+pip3 install -Ir /tmp/etc/requirements.txt
 
 # add pgdg repo to sources
 echo "Writing /etc/apt/sources.list.d/pgdg.list..." >&2
@@ -38,6 +52,11 @@ echo "deb http://apt.postgresql.org/pub/repos/apt/ ${codename}-pgdg main" > \
 echo "Installing server-dev packages..." >&2
 sd_pkgs=( "${pg_majors[@]/#/postgresql-server-dev-}" )
 apt-get update && apt-get install -y --no-install-recommends "${sd_pkgs[@]}"
+
+# build list of postgres
+echo "Installing postgres packages..." >&2
+pg_pkgs=( "${pg_majors[@]/#/postgresql-}" )
+apt-get install -y --no-install-recommends "${pg_pkgs[@]}"
 
 # install old citus versions
 for citus_version in "${citus_versions[@]}"
@@ -74,6 +93,12 @@ do
     build_ext "${pg_major}" "${citus_version}"
     done
 done
+
+chmod o+w -R /usr/
+chmod a+w /var/run/postgresql
+
+apt-get update && apt-get install -y gosu
+
 # keep that image size small!
 echo "Cleaning up..." >&2
 rm -rf /var/lib/apt/lists/*
